In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('cheating_network_edges.csv')
df

,source,target,edge_type,confidence,timestamp,source_year,target_year,source_major,target_major
0,S001,S140,code_copying,0.799460,2026-06-21 21:49:50.113079,2,4,BIO,MATH
1,S001,S139,exam_sharing,0.281209,2026-09-01 21:49:50.113194,2,4,BIO,PHYS
2,S001,S102,answer_distribution,0.414888,2026-07-18 21:49:50.113308,2,3,BIO,PHYS
3,S001,S096,exam_sharing,0.263272,2026-07-07 21:49:50.113423,2,3,BIO,ENG
4,S001,S092,essay_sharing,0.269575,2026-07-04 21:49:50.132531,2,3,BIO,BIO
...,...,...,...,...,...,...,...,...,...
130,S191,S170,essay_sharing,0.713186,2026-08-02 21:49:50.122224,1,1,ENG,ENG
131,S194,S172,essay_sharing,0.453615,2026-08-23 21:49:50.141579,3,1,CHEM,MATH
132,S199,S122,essay_sharing,0.225002,2026-07-01 21:49:50.130480,2,3,CS,ENG
133,S199,S106,code_copying,0.632314,2026-06-10 21:49:50.130597,2,1,CS,PHYS
134,S199,S041,answer_distribution,0.845495,2026-08-25 21:49:50.130712,2,1,CS,CS

In [ ]:
import requests
url = 'https://raw.githubusercontent.com/PacktPublishing/100-Plus-Days-of-Machine-Learning/master/015%20Working%20with%20CSV%20files/cheating_network_edges.csv'
response = requests.get(url)
df = pd.read_csv(response.content)
df

In [8]:
# set parameter
# df = pd.read_csv('cheating_network_edges.tsv', sep='\t')
df=pd.read_csv('cheating_network_edges.csv',names=['source', 'target'] )
df

                                                                                                                source  \
source target edge_type           confidence          timestamp                  source_year target_year  source_major
S001   S140   code_copying        0.7994596861733998  2026-06-21 21:49:50.113079 2           4                     BIO
       S139   exam_sharing        0.28120864499749615 2026-09-01 21:49:50.113194 2           4                     BIO
       S102   answer_distribution 0.41488811558718125 2026-07-18 21:49:50.113308 2           3                     BIO
       S096   exam_sharing        0.26327231273499424 2026-07-07 21:49:50.113423 2           3                     BIO
...                                                                                                                ...
S191   S170   essay_sharing       0.7131858529103655  2026-08-02 21:49:50.122224 1           1                     ENG
S194   S172   essay_sharing       0.45361541340235617 2026-08-23 21:49:50.141579 3           1                    CHEM
S199   S122   essay_sharing       0.22500215104515633 2026-07-01 21:49:50.130480 2           3                      CS
       S106   code_copying        0.63231445291644    2026-06-10 21:49:50.130597 2           1                      CS
       S041   answer_distribution 0.8454952066279521  2026-08-25 21:49:50.130712 2           1                      CS

                                                                                                                target
source target edge_type           confidence          timestamp                  source_year target_year  target_major
S001   S140   code_copying        0.7994596861733998  2026-06-21 21:49:50.113079 2           4                    MATH
       S139   exam_sharing        0.28120864499749615 2026-09-01 21:49:50.113194 2           4                    PHYS
       S102   answer_distribution 0.41488811558718125 2026-07-18 21:49:50.113308 2           3                    PHYS
       S096   exam_sharing        0.26327231273499424 2026-07-07 21:49:50.113423 2           3                     ENG
...                                                                                                                ...
S191   S170   essay_sharing       0.7131858529103655  2026-08-02 21:49:50.122224 1           1                     ENG
S194   S172   essay_sharing       0.45361541340235617 2026-08-23 21:49:50.141579 3           1                    MATH
S199   S122   essay_sharing       0.22500215104515633 2026-07-01 21:49:50.130480 2           3                     ENG
       S106   code_copying        0.63231445291644    2026-06-10 21:49:50.130597 2           1                    PHYS
       S041   answer_distribution 0.8454952066279521  2026-08-25 21:49:50.130712 2           1                      CS

[136 rows x 2 columns]

In [12]:
# index_col parameter
df=pd.read_csv('cheating_network_edges.csv', index_col=0)
df

,target,edge_type,confidence,timestamp,source_year,target_year,source_major,target_major
source,,,,,,,,
S001,S140,code_copying,0.799460,2026-06-21 21:49:50.113079,2,4,BIO,MATH
S001,S139,exam_sharing,0.281209,2026-09-01 21:49:50.113194,2,4,BIO,PHYS
S001,S102,answer_distribution,0.414888,2026-07-18 21:49:50.113308,2,3,BIO,PHYS
S001,S096,exam_sharing,0.263272,2026-07-07 21:49:50.113423,2,3,BIO,ENG
S001,S092,essay_sharing,0.269575,2026-07-04 21:49:50.132531,2,3,BIO,BIO
...,...,...,...,...,...,...,...,...
S191,S170,essay_sharing,0.713186,2026-08-02 21:49:50.122224,1,1,ENG,ENG
S194,S172,essay_sharing,0.453615,2026-08-23 21:49:50.141579,3,1,CHEM,MATH
S199,S122,essay_sharing,0.225002,2026-07-01 21:49:50.130480,2,3,CS,ENG
S199,S106,code_copying,0.632314,2026-06-10 21:49:50.130597,2,1,CS,PHYS
S199,S041,answer_distribution,0.845495,2026-08-25 21:49:50.130712,2,1,CS,CS

In [14]:
# header parameter
df=pd.read_csv('cheating_network_edges.csv', header=1)
df

,S001,S140,code_copying,0.7994596861733998,2026-06-21 21:49:50.113079,2,4,BIO,MATH
0,S001,S139,exam_sharing,0.281209,2026-09-01 21:49:50.113194,2,4,BIO,PHYS
1,S001,S102,answer_distribution,0.414888,2026-07-18 21:49:50.113308,2,3,BIO,PHYS
2,S001,S096,exam_sharing,0.263272,2026-07-07 21:49:50.113423,2,3,BIO,ENG
3,S001,S092,essay_sharing,0.269575,2026-07-04 21:49:50.132531,2,3,BIO,BIO
4,S001,S156,exam_sharing,0.351209,2026-08-14 21:49:50.132646,2,1,BIO,ENG
...,...,...,...,...,...,...,...,...,...
129,S191,S170,essay_sharing,0.713186,2026-08-02 21:49:50.122224,1,1,ENG,ENG
130,S194,S172,essay_sharing,0.453615,2026-08-23 21:49:50.141579,3,1,CHEM,MATH
131,S199,S122,essay_sharing,0.225002,2026-07-01 21:49:50.130480,2,3,CS,ENG
132,S199,S106,code_copying,0.632314,2026-06-10 21:49:50.130597,2,1,CS,PHYS
133,S199,S041,answer_distribution,0.845495,2026-08-25 21:49:50.130712,2,1,CS,CS

In [16]:
# use_cols parameter
df=pd.read_csv('cheating_network_edges.csv', usecols=['source', 'target'])
df

    source target
0     S001   S140
1     S001   S139
2     S001   S102
3     S001   S096
4     S001   S092
..     ...    ...
130   S191   S170
131   S194   S172
132   S199   S122
133   S199   S106
134   S199   S041

[135 rows x 2 columns]

In [21]:
# skiprows parameter
df=pd.read_csv('cheating_network_edges.csv', skiprows=[0,1])
df
# # nrows parameter
df=pd.read_csv('cheating_network_edges.csv', nrows=5)
df

,source,target,edge_type,confidence,timestamp,source_year,target_year,source_major,target_major
0,S001,S140,code_copying,0.799460,2026-06-21 21:49:50.113079,2,4,BIO,MATH
1,S001,S139,exam_sharing,0.281209,2026-09-01 21:49:50.113194,2,4,BIO,PHYS
2,S001,S102,answer_distribution,0.414888,2026-07-18 21:49:50.113308,2,3,BIO,PHYS
3,S001,S096,exam_sharing,0.263272,2026-07-07 21:49:50.113423,2,3,BIO,ENG
4,S001,S092,essay_sharing,0.269575,2026-07-04 21:49:50.132531,2,3,BIO,BIO

In [22]:
# encoding parameter
df=pd.read_csv('cheating_network_edges.csv', encoding='utf-8')
df

,source,target,edge_type,confidence,timestamp,source_year,target_year,source_major,target_major
0,S001,S140,code_copying,0.799460,2026-06-21 21:49:50.113079,2,4,BIO,MATH
1,S001,S139,exam_sharing,0.281209,2026-09-01 21:49:50.113194,2,4,BIO,PHYS
2,S001,S102,answer_distribution,0.414888,2026-07-18 21:49:50.113308,2,3,BIO,PHYS
3,S001,S096,exam_sharing,0.263272,2026-07-07 21:49:50.113423,2,3,BIO,ENG
4,S001,S092,essay_sharing,0.269575,2026-07-04 21:49:50.132531,2,3,BIO,BIO
...,...,...,...,...,...,...,...,...,...
130,S191,S170,essay_sharing,0.713186,2026-08-02 21:49:50.122224,1,1,ENG,ENG
131,S194,S172,essay_sharing,0.453615,2026-08-23 21:49:50.141579,3,1,CHEM,MATH
132,S199,S122,essay_sharing,0.225002,2026-07-01 21:49:50.130480,2,3,CS,ENG
133,S199,S106,code_copying,0.632314,2026-06-10 21:49:50.130597,2,1,CS,PHYS
134,S199,S041,answer_distribution,0.845495,2026-08-25 21:49:50.130712,2,1,CS,CS

In [23]:
# skip bad lines parameter
df=pd.read_csv('cheating_network_edges.csv', error_bad_lines=False)
df

TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'. Did you mean 'on_bad_lines'?

In [24]:
# dtypes parameter
df=pd.read_csv('cheating_network_edges.csv', dtype={'source': str, 'target': str})
df

,source,target,edge_type,confidence,timestamp,source_year,target_year,source_major,target_major
0,S001,S140,code_copying,0.799460,2026-06-21 21:49:50.113079,2,4,BIO,MATH
1,S001,S139,exam_sharing,0.281209,2026-09-01 21:49:50.113194,2,4,BIO,PHYS
2,S001,S102,answer_distribution,0.414888,2026-07-18 21:49:50.113308,2,3,BIO,PHYS
3,S001,S096,exam_sharing,0.263272,2026-07-07 21:49:50.113423,2,3,BIO,ENG
4,S001,S092,essay_sharing,0.269575,2026-07-04 21:49:50.132531,2,3,BIO,BIO
...,...,...,...,...,...,...,...,...,...
130,S191,S170,essay_sharing,0.713186,2026-08-02 21:49:50.122224,1,1,ENG,ENG
131,S194,S172,essay_sharing,0.453615,2026-08-23 21:49:50.141579,3,1,CHEM,MATH
132,S199,S122,essay_sharing,0.225002,2026-07-01 21:49:50.130480,2,3,CS,ENG
133,S199,S106,code_copying,0.632314,2026-06-10 21:49:50.130597,2,1,CS,PHYS
134,S199,S041,answer_distribution,0.845495,2026-08-25 21:49:50.130712,2,1,CS,CS

In [ ]:
# handling dates
df=pd.read_csv('cheating_network_edges.csv', parse_dates=['date'])
df

In [26]:
# convertors parameter
df=pd.read_csv('cheating_network_edges.csv', converters={'source': str, 'target': str})
df

,source,target,edge_type,confidence,timestamp,source_year,target_year,source_major,target_major
0,S001,S140,code_copying,0.799460,2026-06-21 21:49:50.113079,2,4,BIO,MATH
1,S001,S139,exam_sharing,0.281209,2026-09-01 21:49:50.113194,2,4,BIO,PHYS
2,S001,S102,answer_distribution,0.414888,2026-07-18 21:49:50.113308,2,3,BIO,PHYS
3,S001,S096,exam_sharing,0.263272,2026-07-07 21:49:50.113423,2,3,BIO,ENG
4,S001,S092,essay_sharing,0.269575,2026-07-04 21:49:50.132531,2,3,BIO,BIO
...,...,...,...,...,...,...,...,...,...
130,S191,S170,essay_sharing,0.713186,2026-08-02 21:49:50.122224,1,1,ENG,ENG
131,S194,S172,essay_sharing,0.453615,2026-08-23 21:49:50.141579,3,1,CHEM,MATH
132,S199,S122,essay_sharing,0.225002,2026-07-01 21:49:50.130480,2,3,CS,ENG
133,S199,S106,code_copying,0.632314,2026-06-10 21:49:50.130597,2,1,CS,PHYS
134,S199,S041,answer_distribution,0.845495,2026-08-25 21:49:50.130712,2,1,CS,CS

In [27]:
# na_values parameter
df=pd.read_csv('cheating_network_edges.csv', na_values=['NA', 'NaN'])
df

,source,target,edge_type,confidence,timestamp,source_year,target_year,source_major,target_major
0,S001,S140,code_copying,0.799460,2026-06-21 21:49:50.113079,2,4,BIO,MATH
1,S001,S139,exam_sharing,0.281209,2026-09-01 21:49:50.113194,2,4,BIO,PHYS
2,S001,S102,answer_distribution,0.414888,2026-07-18 21:49:50.113308,2,3,BIO,PHYS
3,S001,S096,exam_sharing,0.263272,2026-07-07 21:49:50.113423,2,3,BIO,ENG
4,S001,S092,essay_sharing,0.269575,2026-07-04 21:49:50.132531,2,3,BIO,BIO
...,...,...,...,...,...,...,...,...,...
130,S191,S170,essay_sharing,0.713186,2026-08-02 21:49:50.122224,1,1,ENG,ENG
131,S194,S172,essay_sharing,0.453615,2026-08-23 21:49:50.141579,3,1,CHEM,MATH
132,S199,S122,essay_sharing,0.225002,2026-07-01 21:49:50.130480,2,3,CS,ENG
133,S199,S106,code_copying,0.632314,2026-06-10 21:49:50.130597,2,1,CS,PHYS
134,S199,S041,answer_distribution,0.845495,2026-08-25 21:49:50.130712,2,1,CS,CS

In [28]:
# load huge files in chunks
chunk_size = 1000
for chunk in pd.read_csv('cheating_network_edges.csv', chunksize=chunk_size):
    # Process each chunk here
    print(chunk)

    source target            edge_type  confidence  \
0     S001   S140         code_copying    0.799460
1     S001   S139         exam_sharing    0.281209
2     S001   S102  answer_distribution    0.414888
3     S001   S096         exam_sharing    0.263272
4     S001   S092        essay_sharing    0.269575
..     ...    ...                  ...         ...
130   S191   S170        essay_sharing    0.713186
131   S194   S172        essay_sharing    0.453615
132   S199   S122        essay_sharing    0.225002
133   S199   S106         code_copying    0.632314
134   S199   S041  answer_distribution    0.845495

                      timestamp  source_year  target_year source_major  \
0    2026-06-21 21:49:50.113079            2            4          BIO
1    2026-09-01 21:49:50.113194            2            4          BIO
2    2026-07-18 21:49:50.113308            2            3          BIO
3    2026-07-07 21:49:50.113423            2            3          BIO
4    2026-07-04 21:49:50.132531            2            3          BIO
..                          ...          ...          ...          ...
130  2026-08-02 21:49:50.122224            1            1          ENG
131  2026-08-23 21:49:50.141579            3            1         CHEM
132  2026-07-01 21:49:50.130480            2            3           CS
133  2026-06-10 21:49:50.130597            2            1           CS
134  2026-08-25 21:49:50.130712            2            1           CS

    target_major
0           MATH
1           PHYS
2           PHYS
3            ENG
4            BIO
..           ...
130          ENG
131         MATH
132          ENG
133         PHYS
134           CS

[135 rows x 9 columns]